### ISSUE TITLE
Difficulty idea

### ISSUE THREAD

**Issue by TebexPL** [Toriality/DYOM-Bingo#12]
Each slot already has an array of requirements, adding "difficulty-low", "difficulty-medium" or "difficulty-high" to every slot, then adding options "limit easy", "limit medium", "limit difficult" would allow users to adjust difficulty.

Of course adding difficulty selection can be done in different ways, the one described above seems to be simple and fast to implement

**Comment by Toriality** [comment]
It is a bit subjective to detect how difficult a slot is. Of course some things usually occur more frequently than others, but since missions appear randomly, establishing difficulty would be a bit tricky.

And I'm not sure it would be a feature that would be used much either. 

I'm open to a second thought tho.
